let songs = [
  {
    imageSource: 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Continuum_by_John_Mayer_%282006%29.jpg',
    musicSource: require('../music/Gravity.mp3'),
    key: '1',
    name: 'Gravity',
    artist: 'John Mayer',
    favorite: true,
  },
  {
    imageSource: 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Continuum_by_John_Mayer_%282006%29.jpg',
    musicSource: require('../music/InRepair.mp3'),
    key: '2',
    name: 'In Repair',
    artist: 'John Mayer',
    favorite: false,
  },
  {
    imageSource: 'https://direct.rhapsody.com/imageserver/images/alb.232331272/500x500.jpg',
    musicSource: require('../music/ItsBeen.mp3'),
    key: '3',
    name: 'Its been a long, long time',
    artist: 'Harry James',
    favorite: false,
  },
  {
    imageSource: 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Continuum_by_John_Mayer_%282006%29.jpg',
    musicSource: require('../music/Gravity.mp3'),
    key: '4',
    name: 'Gravity',
    artist: 'John Mayer',
    favorite: true,
  },
  {
    imageSource: 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Continuum_by_John_Mayer_%282006%29.jpg',
    musicSource: require('../music/InRepair.mp3'),
    key: '5',
    name: 'In Repair',
    artist: 'John Mayer',
    favorite: false,
  },
  {
    imageSource: 'https://direct.rhapsody.com/imageserver/images/alb.232331272/500x500.jpg',
    musicSource: require('../music/ItsBeen.mp3'),
    key: '6',
    name: 'Its been a long, long time',
    artist: 'Harry James',
    favorite: false,
  },
  {
    imageSource: 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Continuum_by_John_Mayer_%282006%29.jpg',
    musicSource: require('../music/Gravity.mp3'),
    key: '7',
    name: 'Gravity',
    artist: 'John Mayer',
    favorite: true,
  },
  {
    imageSource: 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Continuum_by_John_Mayer_%282006%29.jpg',
    musicSource: require('../music/InRepair.mp3'),
    key: '8',
    name: 'In Repair',
    artist: 'John Mayer',
    favorite: false,
  },
  {
    imageSource: 'https://direct.rhapsody.com/imageserver/images/alb.232331272/500x500.jpg',
    musicSource: require('../music/ItsBeen.mp3'),
    key: '9',
    name: 'Its been a long, long time',
    artist: 'Harry James',
    favorite: false,
  },
];

export default songs;